services:
  frontend:
    build: ./frontend
    container_name: findmymate_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: findmymate_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/findmymate
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  db:
    image: postgres:16
    container_name: findmymate_db
    environment:
      POSTGRES_DB: findmymate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: